# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a321511ef819a154aa5554786ef43e130594318dbccf6395e3466acb2d802a12a643446371d4f6a8e595cb98c761b289d2a7f89e66296b6e5d60de408fd0064d

test:
  secret_key_base: f6da06ff8d7234fdac977d9c50d9f16a68d905b440d7375bbe8a0d371e7e2ca4747c3ff443bfa4f07a5434511a973689c849a88e8291ee236931ca5b9f02bbdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
